import React from 'react';
import {
    Monitor, Terminal, Globe, Folder, Search,
    ArrowUp, ArrowDown, ArrowLeft, ArrowRight,
    ChevronUp, ChevronDown, ChevronLeft, ChevronRight,
    X, Minimize, Maximize, Copy, Scissors, Undo, Redo,
    Power, Settings, Home, Lock, RefreshCw, LogOut,
    Sun, SunDim, Moon,
    Play, Pause, SkipBack, SkipForward, FastForward, Rewind,
    Volume, Volume1, Volume2, VolumeX, Mic, MicOff, Camera, CameraOff,
    Code, Zap, Gamepad2, FileText, Briefcase, Mail, Calendar, Clipboard, CheckSquare,
    Database, Server, Bug, LayoutDashboard, Cpu, GitBranch,
    Activity, Heart, Flame, Trophy, Timer
} from 'lucide-react';

export const COLOR_PRESETS = [
    'transparent', '#1f2937', '#ef4444', '#22c55e',
    '#3b82f6', '#eab308', '#a855f7', '#ec4899'
];

export const ICON_PRESETS = [
    { id: 'Monitor', icon: Monitor },
    { id: 'Terminal', icon: Terminal },
    { id: 'Globe', icon: Globe },
    { id: 'Folder', icon: Folder },
    { id: 'Search', icon: Search },
    { id: 'ArrowUp', icon: ArrowUp },
    { id: 'ArrowDown', icon: ArrowDown },
    { id: 'ArrowLeft', icon: ArrowLeft },
    { id: 'ArrowRight', icon: ArrowRight },
    { id: 'ChevronUp', icon: ChevronUp },
    { id: 'ChevronDown', icon: ChevronDown },
    { id: 'ChevronLeft', icon: ChevronLeft },
    { id: 'ChevronRight', icon: ChevronRight },
    { id: 'X', icon: X },
    { id: 'Minimize', icon: Minimize },
    { id: 'Maximize', icon: Maximize },
    { id: 'Copy', icon: Copy },
    { id: 'Scissors', icon: Scissors },
    { id: 'Undo', icon: Undo },
    { id: 'Redo', icon: Redo },
    { id: 'Power', icon: Power },
    { id: 'Settings', icon: Settings },
    { id: 'Home', icon: Home },
    { id: 'Lock', icon: Lock },
    { id: 'RefreshCw', icon: RefreshCw },
    { id: 'LogOut', icon: LogOut },
    { id: 'Sun', icon: Sun },
    { id: 'SunDim', icon: SunDim },
    { id: 'Moon', icon: Moon },
    { id: 'Play', icon: Play },
    { id: 'Pause', icon: Pause },
    { id: 'SkipBack', icon: SkipBack },
    { id: 'SkipForward', icon: SkipForward },
    { id: 'FastForward', icon: FastForward },
    { id: 'Rewind', icon: Rewind },
    { id: 'Volume', icon: Volume },
    { id: 'Volume1', icon: Volume1 },
    { id: 'Volume2', icon: Volume2 },
    { id: 'VolumeX', icon: VolumeX },
    { id: 'Mic', icon: Mic },
    { id: 'MicOff', icon: MicOff },
    { id: 'Camera', icon: Camera },
    { id: 'CameraOff', icon: CameraOff },
    { id: 'Code', icon: Code },
    { id: 'Zap', icon: Zap },
    { id: 'Gamepad2', icon: Gamepad2 },
    { id: 'FileText', icon: FileText },
    { id: 'Briefcase', icon: Briefcase },
    { id: 'Mail', icon: Mail },
    { id: 'Calendar', icon: Calendar },
    { id: 'Clipboard', icon: Clipboard },
    { id: 'CheckSquare', icon: CheckSquare },
    { id: 'Database', icon: Database },
    { id: 'Server', icon: Server },
    { id: 'Bug', icon: Bug },
    { id: 'LayoutDashboard', icon: LayoutDashboard },
    { id: 'Cpu', icon: Cpu },
    { id: 'GitBranch', icon: GitBranch },
    { id: 'Activity', icon: Activity },
    { id: 'Heart', icon: Heart },
    { id: 'Flame', icon: Flame },
    { id: 'Trophy', icon: Trophy },
    { id: 'Timer', icon: Timer }
];
export const CATALOG_PRESETS = [
    { id: 'adobe-lightroom', label: 'Lightroom' },
    { id: 'adobe-photoshop', label: 'Photoshop' },
    { id: 'adobe-premiere', label: 'Adobe remiere' },
    { id: 'adobe-xd', label: 'Adobe XD' },
    { id: 'apple-macbook-iphone', label: 'Apple' },
    { id: 'blender', label: 'Blender' },
    { id: 'brave', label: 'Brave' },
    { id: 'chrome', label: 'Chrome' },
    { id: 'clion', label: 'CLion' },
    { id: 'discord', label: 'Discord' },
    { id: 'docker', label: 'Docker' },
    { id: 'edge', label: 'Edge' },
    { id: 'figma', label: 'Figma' },
    { id: 'finder', label: 'Finder' },
    { id: 'firefox', label: 'Firefox' },
    { id: 'github', label: 'GitHub' },
    { id: 'google', label: 'Google' },
    { id: 'google-meet', label: 'Google Meet' },
    { id: 'hackclub', label: 'Hack Club' },
    { id: 'kubernetes', label: 'Kubernetes' },
    { id: 'linkedin', label: 'LinkedIn' },
    { id: 'postman-icon', label: 'Postman' },
    { id: 'pycharm', label: 'PyCharm' },
    { id: 'safari-ios', label: 'Safari' },
    { id: 'slack', label: 'Slack' },
    { id: 'spotify-color', label: 'Spotify' },
    { id: 'stackoverflow-icon', label: 'Stack Overflow' },
    { id: 'teams', label: 'Teams' },
    { id: 'twitch', label: 'Twitch' },
    { id: 'vs-code', label: 'VS Code' },
    { id: 'webstorm', label: 'WebStorm' },
    { id: 'whatsapp-color', label: 'WhatsApp' },
    { id: 'windows-applications', label: 'Windows' },
    { id: 'youtube', label: 'YouTube' }
];


export const ICON_MAP: Record<string, React.ElementType> = ICON_PRESETS.reduce((acc, curr) => {
    acc[curr.id] = curr.icon;
    return acc;
}, {} as Record<string, React.ElementType>);